graph TD;
    A[Benvinguda] --> B[Login]
    B --> C[Listat de nens]
    C --> D[Nens]
    B --> D
    B --> E[Registrar User / Nen]
    B --> F[He oblidat la contrasenya]
    F-->B
    D --> G[Cuidador <br>afegir / modificar / eliminar]
    D --> H[Editar perfil]
    D --> I[Editar info nen]
    E --> D