@startuml
left to right direction

actor "Usuari Generic" as generic_user
actor "Usuari Tutor" as tutor_user
actor "Usuari Cuidador" as cuidador_user
tutor_user -|> generic_user
cuidador_user -|> generic_user

usecase "Login" as UC1
usecase "Consulta Child" as UC2
usecase "Add Child" as UC3
usecase "Add Taps Child" as UC4
usecase "Consulta Taps Child" as UC5
(Consulta User) as UC6
(Calcular Temps pegat) as UC7
(Cconsulta Child) as UC8


generic_user --> UC1
tutor_user --> UC2
tutor_user --> UC3
tutor_user --> UC4
tutor_user --> UC5
cuidador_user --> UC2
cuidador_user --> UC4
cuidador_user --> UC5
UC2 <-- UC6 : include
UC4 <-- UC7 : extends
UC5 <-- UC8 : include
@enduml