---
title: Diagrama de la classe Client
---
classDiagram
    Vista --> Client_DAO_User
    Client_DAO_User --> Usuari
    Client_DAO_User --> Vista
    
    class Vista{
        +User user
        +String username
        +getUserByUsername()
        +mostrarInformacioUser(id, username, email): void
        +mostrarError(missatge): void
    }

    class Client_DAO_User{
    +String username
        +getUserByUsername(): UserData or Error
        %% +enviarPeticioHTTP(username, password): void
        %% +processarRespostaHTTP(resposta): void
    }

    class Usuari{
        -int id
        +String userName
        +String email
        -String password
        +demanarDades(username): void
    }
    class Error{
        +int code
        +String descripcio
    }
