---
title: Diagrama de la classe Client | Prototip 1
---
classDiagram
    Vista --> Client_DAO_User
    
    class Vista{
        +String username
        +getUserByConsole()
        +mostrarInformacioUser(User usuari)
        +mostrarError(Error missatge)
    }

    class Client_DAO_User{
    +String username
        +getUserByUsername(): UserData or Error
        %% +enviarPeticioHTTP(username, password): void
        %% +processarRespostaHTTP(resposta): void
    }

    class Usuari{
        -int id
        +String username
        +String email
        -String password
    }
    class Error{
        +int code
        +String descripcio
    }
